name: CI

on:
  pull_request:
    branches:
    - master


jobs:
  node-ci:
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.15.1'
    - run: npm install
    - name: npm install and cat
      run: |
        npm install
        cat /.github/workflows/main.yml
      env:
        CI: true
